name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Typecheck & Lint (best-effort)
        run: |
          npm run -s typecheck || true
          npm run -s lint || true

      - name: Build frontend
        run: npm run build

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust fmt check
        run: cargo fmt --all -- --check

      - name: Cargo check (tauri)
        working-directory: src-tauri
        run: cargo check
